### ISSUE TITLE
Line moves unexpextedly

### ISSUE THREAD

**Issue by pmagnussen** [GoogleChromeLabs/rotavo#3]
Hard to explain this one, so I thought I’d share this video instead.
https://youtu.be/jVva3M6Ihuk

Environment:
Apple iPad
iOS 12.1.1 (16C50)
Google Chrome 64.0.3282.112

**Comment by rowan-m** [comment]
This should be fixed now. The issue was the line drawing optimisation kicking in at the end of the screen, but having a previous vector of 0 - so it was mistakenly overwriting the previous segment.
If you could take a peek at https://rotavo-pwa.firebaseapp.com/ on your device to verify that would be grand!
